"""EDOPro replay and ocgcore message constants (from edopro replay.h + echelon estimation.rs)."""

REPLAY_COMPRESSED = 0x1
REPLAY_TAG = 0x2
REPLAY_DECODED = 0x4
REPLAY_SINGLE_MODE = 0x8
REPLAY_LUA64 = 0x10
REPLAY_NEWREPLAY = 0x20
REPLAY_HAND_TEST = 0x40
REPLAY_DIRECT_SEED = 0x80
REPLAY_64BIT_DUELFLAG = 0x100
REPLAY_EXTENDED_HEADER = 0x200

REPLAY_YRP1 = 0x31707279
REPLAY_YRPX = 0x58707279

OLD_REPLAY_MODE = 231

MSG_HINT = 2
MSG_START = 4
MSG_WIN = 5
MSG_UPDATE_DATA = 6
MSG_UPDATE_CARD = 7
MSG_CONFIRM_DECKTOP = 30
MSG_CONFIRM_CARDS = 31
MSG_SHUFFLE_DECK = 32
MSG_SHUFFLE_HAND = 33
MSG_SHUFFLE_SET_CARD = 36
MSG_NEW_TURN = 40
MSG_NEW_PHASE = 41

# ocgapi_constants.h — single-bit phase values in MSG_NEW_PHASE (uint16 LE)
PHASE_DRAW = 0x01
PHASE_STANDBY = 0x02
PHASE_MAIN1 = 0x04
PHASE_BATTLE_START = 0x08
PHASE_BATTLE = 0x80
PHASE_MAIN2 = 0x100
PHASE_END = 0x200
MSG_CONFIRM_EXTRATOP = 42
MSG_MOVE = 50
MSG_POS_CHANGE = 53
MSG_SET = 54
MSG_SWAP = 55
MSG_SUMMONING = 60
MSG_SUMMONED = 61
MSG_SPSUMMONING = 62
MSG_SPSUMMONED = 63
MSG_FLIPSUMMONING = 64
MSG_FLIPSUMMONED = 65
MSG_CHAINING = 70
MSG_CHAINED = 71
MSG_CHAIN_SOLVING = 72
MSG_CHAIN_SOLVED = 73
MSG_CHAIN_END = 74
MSG_CHAIN_NEGATED = 75
MSG_CHAIN_DISABLED = 76
MSG_RANDOM_SELECTED = 81
MSG_BECOME_TARGET = 83
MSG_DRAW = 90
MSG_DAMAGE = 91
MSG_RECOVER = 92
MSG_EQUIP = 93
MSG_LPUPDATE = 94
MSG_UNEQUIP = 95
MSG_CARD_TARGET = 96
MSG_CANCEL_TARGET = 97
MSG_PAY_LPCOST = 100
MSG_ADD_COUNTER = 101
MSG_REMOVE_COUNTER = 102
MSG_ATTACK = 110
MSG_BATTLE = 111
MSG_ATTACK_DISABLED = 112
MSG_TOSS_COIN = 130
MSG_TOSS_DICE = 131
MSG_TAG_SWAP = 161
MSG_RELOAD_FIELD = 162
MSG_AI_NAME = 200

HINT_OPSELECTED = 4
HINT_EFFECT = 5
HINT_RACE = 6
HINT_ATTRIB = 7
HINT_CODE = 8
HINT_NUMBER = 9
HINT_CARD = 10
HINT_ZONE = 11

MSG_NAMES = {
    MSG_HINT: "HINT",
    MSG_START: "START",
    MSG_WIN: "WIN",
    MSG_UPDATE_DATA: "UPDATE_DATA",
    MSG_UPDATE_CARD: "UPDATE_CARD",
    MSG_NEW_TURN: "NEW_TURN",
    MSG_NEW_PHASE: "NEW_PHASE",
    MSG_MOVE: "MOVE",
    MSG_POS_CHANGE: "POS_CHANGE",
    MSG_SET: "SET",
    MSG_SUMMONED: "SUMMONED",
    MSG_SPSUMMONED: "SPSUMMONED",
    MSG_FLIPSUMMONED: "FLIPSUMMONED",
    MSG_CHAINING: "CHAINING",
    MSG_CHAINED: "CHAINED",
    MSG_CHAIN_SOLVING: "CHAIN_SOLVING",
    MSG_CHAIN_SOLVED: "CHAIN_SOLVED",
    MSG_CHAIN_END: "CHAIN_END",
    MSG_CHAIN_NEGATED: "CHAIN_NEGATED",
    MSG_CHAIN_DISABLED: "CHAIN_DISABLED",
    MSG_DRAW: "DRAW",
    MSG_DAMAGE: "DAMAGE",
    MSG_RECOVER: "RECOVER",
    MSG_LPUPDATE: "LPUPDATE",
    MSG_ATTACK: "ATTACK",
    MSG_BATTLE: "BATTLE",
    MSG_PAY_LPCOST: "PAY_LPCOST",
    MSG_TOSS_COIN: "TOSS_COIN",
    MSG_TOSS_DICE: "TOSS_DICE",
    MSG_RELOAD_FIELD: "RELOAD_FIELD",
    OLD_REPLAY_MODE: "OLD_REPLAY_MODE",
}

# Messages worth recording in full event trace
TRACKED_MSG = frozenset(
    {
        MSG_START,
        MSG_WIN,
        MSG_NEW_TURN,
        MSG_NEW_PHASE,
        MSG_HINT,
        MSG_MOVE,
        MSG_POS_CHANGE,
        MSG_SET,
        MSG_SUMMONED,
        MSG_SPSUMMONED,
        MSG_FLIPSUMMONED,
        MSG_CHAINING,
        MSG_CHAINED,
        MSG_CHAIN_END,
        MSG_CHAIN_NEGATED,
        MSG_CHAIN_DISABLED,
        MSG_DRAW,
        MSG_DAMAGE,
        MSG_RECOVER,
        MSG_LPUPDATE,
        MSG_ATTACK,
        MSG_BATTLE,
        MSG_PAY_LPCOST,
        MSG_TOSS_COIN,
        MSG_TOSS_DICE,
        MSG_CONFIRM_CARDS,
        MSG_CONFIRM_DECKTOP,
        MSG_SHUFFLE_HAND,
        MSG_SHUFFLE_DECK,
        OLD_REPLAY_MODE,
    }
)

# echelon duration heuristic (frames at 60fps)
DURATION_SKIP_MSG = frozenset(
    {
        MSG_START,
        MSG_UPDATE_DATA,
        MSG_UPDATE_CARD,
        MSG_SET,
        MSG_SWAP,
        MSG_SUMMONING,
        MSG_SPSUMMONING,
        MSG_FLIPSUMMONING,
        MSG_CHAIN_SOLVING,
        MSG_CHAIN_SOLVED,
        MSG_CHAIN_END,
        MSG_RANDOM_SELECTED,
        MSG_EQUIP,
        MSG_UNEQUIP,
        MSG_CARD_TARGET,
        MSG_CANCEL_TARGET,
        MSG_BATTLE,
        MSG_ATTACK_DISABLED,
        MSG_TAG_SWAP,
        MSG_RELOAD_FIELD,
    }
)
