import argparse
import sqlite3
from pathlib import Path


def iter_db_ids(db_path: Path) -> set[int]:
    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()
        cur.execute("SELECT id FROM datas")
        return {int(r[0]) for r in cur.fetchall()}
    finally:
        con.close()


def main() -> None:
    p = argparse.ArgumentParser(description="Generate a whitelist-style lflist.conf for Saint Seiya cards.")
    p.add_argument("--output", default="lflist.conf", help="Output file path (default: lflist.conf)")
    p.add_argument(
        "--db",
        action="append",
        default=[],
        help="Additional .cdb to pull ids from (repeatable).",
    )
    p.add_argument("--start", type=int, default=922100000)
    p.add_argument("--end", type=int, default=922100171)
    p.add_argument("--list-id", type=int, default=922199001)
    p.add_argument("--list-name", default="Saint Seiya Only (whitelist)")
    args = p.parse_args()

    root = Path.cwd()
    output = Path(args.output)

    allowed = set(range(args.start, args.end + 1))

    db_paths: list[Path] = []
    # Common local locations
    for candidate in [
        root / "cards.cdb",
        root / "expansions" / "cards.cdb",
        root / "expansions" / "cards-unofficial.cdb",
        root / "expansions" / "saint-seiya.cdb",
    ]:
        if candidate.exists():
            db_paths.append(candidate)
    for extra in args.db:
        ep = Path(extra)
        if ep.exists():
            db_paths.append(ep)

    all_ids: set[int] = set()
    for db in dict.fromkeys(db_paths):  # dedupe preserving order
        all_ids |= iter_db_ids(db)

    forbidden = sorted(i for i in all_ids if i not in allowed)
    allowed_present = sorted(i for i in all_ids if i in allowed)
    missing_allowed = sorted(i for i in allowed if i not in all_ids)

    lines: list[str] = []
    lines.append("# Auto-generated by tools/generate_saint_seiya_whitelist_lflist.py")
    lines.append("# NOTE: A whitelist lflist must explicitly FORBID every other card id.")
    lines.append(f"# Allowed range: {args.start}..{args.end}")
    if missing_allowed:
        lines.append(f"# WARNING: {len(missing_allowed)} allowed ids not found in provided DBs (e.g. {missing_allowed[:10]})")
    lines.append("")
    lines.append(f"!list {args.list_id} {args.list_name}")
    lines.append("#forbidden")
    for cid in forbidden:
        lines.append(f"{cid} 0")
    lines.append("#allowed (explicit, max 3)")
    for cid in allowed_present:
        lines.append(f"{cid} 3")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote: {output}")
    print(f"dbs_used: {len(list(dict.fromkeys(db_paths)))}")
    print(f"forbidden: {len(forbidden)}")
    print(f"allowed_present: {len(allowed_present)}")
    print(f"missing_allowed: {len(missing_allowed)}")


if __name__ == "__main__":
    main()

